name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app (test)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: npm run dist:win

      - name: Upload build artifacts (test)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          name: tracker-build
          path: dist/
          retention-days: 7

      - name: Build and publish release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          npm run dist:win
          npm run create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: tracker-release
          path: dist/*.exe
          retention-days: 30
