name: Build (Windows)

on:
  push:
    branches: [ master ]
    tags-ignore: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_BUILDER_DEBUG: "true"
      DEBUG: "electron-builder"
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
      USE_HARD_LINKS: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build renderer
        run: npm run build

      - name: Print versions
        run: |
          node -v
          npm -v
          npx electron-builder --version

      - name: List build dir (pre-build)
        shell: pwsh
        run: |
          if (Test-Path "build") { Write-Host "`n--- build/ ---"; Get-ChildItem -Recurse -Force build | Select-Object FullName,Length | Format-Table -AutoSize }

      - name: Package app (no publish)
        run: npx electron-builder --win

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-win
          path: dist/**
          if-no-files-found: error

      - name: List dist after build
        if: always()
        shell: pwsh
        run: |
          if (Test-Path "dist") { Write-Host "`n--- dist/ ---"; Get-ChildItem -Recurse -Force dist | Select-Object FullName,Length | Format-Table -AutoSize }
